export const businessSolution = [
  "IT Products Dev",
  "IT Products Design & Dev",
  "Financial and Business Plans",
  "Drupal Dev",
  "DevOps",
  "Bitrix24 Dev",
  "App Dev & Des",
  "AI & ML Dev",
  "Data Science, AI, ML",
  "AI Dev",
  "B2B SaaS Dev",
  "Database Dev",
  "Complex Des & Dev",
  "Digital Product Dev",
  "Laravel Dev",
  "Fintech Dev",
  "Wordpress Dev",
  "Boutique Digital Dev",
  "Web & Moblie Dev",
  "Magento development",
  "Digital Product & UX Agency",
  "Web & App Development",
  "Web Design & Development",
  "Web and Mobile Design",
  "IT Products Development & Design",
  "Digital Marketing",
  "Web, Desktop, Mobile Dev",
];
